/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { Star, MessageSquareQuote } from 'lucide-react';

interface Review {
  id: string;
  name: string;
  niche: string;
  subscribers: string;
  avatarColor: string;
  rating: number;
  quote: string;
}

const PLACEHOLDER_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    name: 'Marcus Chen',
    niche: 'Tech Reviews',
    subscribers: '120K subs',
    avatarColor: 'bg-emerald-500',
    rating: 5,
    quote: 'ScriptIQ completely cut down my scripting time. I went from staring at a blank screen for 4 hours to generating an engaging hook and full draft in 10 minutes.'
  },
  {
    id: 'rev-2',
    name: 'Sarah Jenkins',
    niche: 'Gaming & Let\'s Play',
    subscribers: '45K subs',
    avatarColor: 'bg-indigo-500',
    rating: 5,
    quote: 'The hooks generated by ScriptIQ are insanely good. My audience retention on YouTube went up by 15% in the first week of using it.'
  },
  {
    id: 'rev-3',
    name: 'David Kojo',
    niche: 'Education & Science',
    subscribers: '210K subs',
    avatarColor: 'bg-amber-500',
    rating: 4,
    quote: 'Excellent tool for organizing my educational videos. The SEO title and description suggestions helped my last video rank #2 in search results.'
  },
  {
    id: 'rev-4',
    name: 'Elena Rostova',
    niche: 'Daily Vlogging',
    subscribers: '85K subs',
    avatarColor: 'bg-purple-500',
    rating: 5,
    quote: 'I love how intuitive the sandbox is. ScriptIQ helps me structure my thoughts so my vlogs feel punchy, fast-paced, and engaging.'
  }
];

// Custom hook to detect OS prefers-reduced-motion setting
function usePrefersReducedMotion() {
  const [prefersReducedMotion, setPrefersReducedMotion] = useState(false);

  useEffect(() => {
    // Check if window is defined (SSR safety)
    if (typeof window === 'undefined') return;

    const mediaQuery = window.matchMedia('(prefers-reduced-motion: reduce)');
    setPrefersReducedMotion(mediaQuery.matches);

    const listener = (event: MediaQueryListEvent) => {
      setPrefersReducedMotion(event.matches);
    };

    mediaQuery.addEventListener('change', listener);
    return () => {
      mediaQuery.removeEventListener('change', listener);
    };
  }, []);

  return prefersReducedMotion;
}

interface TestimonialsSectionProps {
  density?: 'compact' | 'comfortable';
}

export default function TestimonialsSection({ density = 'compact' }: TestimonialsSectionProps) {
  const prefersReducedMotion = usePrefersReducedMotion();
  const isCompact = density === 'compact';

  // Get initials for review avatar
  const getInitials = (name: string) => {
    return name
      .split(' ')
      .map((part) => part[0])
      .join('')
      .toUpperCase();
  };

  // Render a single review card
  const ReviewCard = ({ review, isDuplicate = false }: { review: Review; isDuplicate?: boolean; key?: React.Key }) => {
    return (
      <div
        className={`bg-white border border-gray-200 rounded-2xl p-5 w-[290px] sm:w-[350px] shrink-0 transition-all duration-300 hover:border-[#4F46E5] hover:-translate-y-1.5 hover:shadow-lg hover:shadow-indigo-500/5 flex flex-col justify-between`}
        tabIndex={isDuplicate ? -1 : 0}
        aria-hidden={isDuplicate}
      >
        <div className="space-y-3">
          {/* Rating */}
          <div className="flex items-center gap-0.5">
            {[1, 2, 3, 4, 5].map((star) => (
              <Star
                key={star}
                className={`w-4 h-4 ${
                  star <= review.rating ? 'text-amber-400 fill-amber-400' : 'text-gray-200'
                }`}
              />
            ))}
          </div>

          {/* Quote */}
          <p className="text-gray-600 text-[11px] sm:text-xs leading-relaxed italic">
            "{review.quote}"
          </p>
        </div>

        {/* User Info */}
        <div className="mt-5 pt-4 border-t border-gray-100 flex items-center gap-3">
          {/* Avatar with Initials */}
          <div className={`w-9 h-9 rounded-full ${review.avatarColor} text-white flex items-center justify-center font-mono text-[11px] font-bold shrink-0 shadow-2xs`}>
            {getInitials(review.name)}
          </div>
          <div className="truncate">
            <h5 className="font-sans font-bold text-gray-900 text-[11px] sm:text-xs leading-none">
              {review.name}
            </h5>
            <span className="text-[10px] text-gray-400 font-medium block mt-1 truncate">
              {review.niche} • {review.subscribers}
            </span>
          </div>
        </div>
      </div>
    );
  };

  return (
    <motion.section
      id="testimonials"
      initial={{ opacity: 0, y: 25 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: '-60px' }}
      transition={{ duration: 0.6, ease: 'easeOut' }}
      className={`bg-gray-50 border-t border-b border-gray-200/60 overflow-hidden relative transition-all duration-150 ${
        isCompact ? 'py-10' : 'py-20'
      }`}
    >
      {/* Visual Accent Circle */}
      <div className="absolute -top-16 -left-16 w-48 h-48 rounded-full bg-indigo-500/5 blur-3xl pointer-events-none" />
      <div className="absolute -bottom-16 -right-16 w-48 h-48 rounded-full bg-indigo-500/5 blur-3xl pointer-events-none" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative">
        {/* Section Header */}
        <div className={`text-center max-w-2xl mx-auto space-y-3 ${isCompact ? 'mb-8' : 'mb-16'}`}>
          <div className="inline-flex items-center gap-1.5 bg-[#4F46E5]/10 border border-[#4F46E5]/20 text-[#4F46E5] font-mono text-[9px] font-bold uppercase tracking-wider px-2.5 py-1 rounded-full">
            <MessageSquareQuote className="w-3 h-3" />
            Social Proof
          </div>
          <h2 className={`font-sans font-bold text-black tracking-tight ${isCompact ? 'text-xl sm:text-2xl' : 'text-3xl sm:text-4xl font-extrabold'}`}>
            Loved by Fast-Growing Creators
          </h2>
          <p className={`font-sans text-gray-500 leading-relaxed ${isCompact ? 'text-xs' : 'text-base'}`}>
            See how ScriptIQ helps creators eliminate writer's block, write high-retention hooks, and streamline their production pipeline.
          </p>
          <div className="inline-block bg-amber-50 text-amber-700 font-mono text-[9px] font-semibold border border-amber-200/60 px-3 py-1 rounded-md">
            ⚠️ Launch Stage Notice: Placeholder content pending final active client reviews
          </div>
        </div>

        {/* Accessibility fallback check indicator for developers/users (discreetly in corner of section) */}
        <div className="absolute top-2 right-4 text-[9px] text-gray-400 font-mono hidden md:block">
          Reduced Motion State: <span className={prefersReducedMotion ? 'text-emerald-600 font-bold' : 'text-gray-500'}>{prefersReducedMotion ? 'ACTIVE (Static Grid)' : 'INACTIVE (Smooth Marquee)'}</span>
        </div>

        {/* Testimonials Body */}
        {prefersReducedMotion ? (
          /* REDUCED MOTION STATIC GRID FALLBACK */
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 max-w-6xl mx-auto px-4">
            {PLACEHOLDER_REVIEWS.map((review) => (
              <div key={review.id} className="flex justify-center">
                <ReviewCard review={review} />
              </div>
            ))}
          </div>
        ) : (
          /* INFINITE HORIZONTAL MARQUEE CAROUSEL */
          <div className="w-full relative overflow-hidden [mask-image:_linear-gradient(to_right,transparent_0,_black_80px,_black_calc(100%-80px),transparent_100%)] select-none">
            <div className="group flex w-max">
              {/* First Track Copy */}
              <div className="flex gap-6 pr-6 shrink-0 animate-marquee group-hover:[animation-play-state:paused]">
                {PLACEHOLDER_REVIEWS.map((review) => (
                  <ReviewCard key={review.id} review={review} />
                ))}
              </div>
              {/* Second Track Copy (Seamless Loop) */}
              <div className="flex gap-6 pr-6 shrink-0 animate-marquee group-hover:[animation-play-state:paused]" aria-hidden="true">
                {PLACEHOLDER_REVIEWS.map((review) => (
                  <ReviewCard key={`${review.id}-duplicate`} review={review} isDuplicate={true} />
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </motion.section>
  );
}
